# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run

on: [pull]
jobs:
  send-pull-events:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: ./pr.sh
